import { writeFileSync, readFileSync, existsSync, mkdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { SOUND_CATEGORIES, getSoundsDir } from "./play-sound.js";

const PLUGIN_FILENAME = "dota2-sounds.js";

/**
 * Get the path to OpenCode's global plugins directory.
 */
export function getOpenCodePluginsDir(): string {
  return join(homedir(), ".config", "opencode", "plugins");
}

/**
 * Get the full path to the plugin file.
 */
export function getOpenCodePluginPath(): string {
  return join(getOpenCodePluginsDir(), PLUGIN_FILENAME);
}

/**
 * Check if OpenCode config directory exists.
 */
export function isOpenCodeAvailable(): boolean {
  return existsSync(join(homedir(), ".config", "opencode"));
}

/**
 * Generate a self-contained OpenCode plugin JS file.
 * The plugin is fully standalone — no imports from this package at runtime.
 * Sound paths are baked in at install time.
 */
function generatePluginSource(soundsDir: string): string {
  const categories = JSON.stringify(SOUND_CATEGORIES, null, 2);

  return `// Auto-generated by dota2-code-sounds — do not edit manually
// Dota 2 Axe voice line notifications for OpenCode
import { execFile } from "node:child_process";

const SOUNDS_DIR = ${JSON.stringify(soundsDir)};

const CATEGORIES = ${categories};

const ALL_SOUNDS = Object.values(CATEGORIES).flat();

function randomPick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function playSound(category) {
  const sounds = CATEGORIES[category] ?? ALL_SOUNDS;
  const soundFile = randomPick(sounds);
  const soundPath = SOUNDS_DIR + "/" + soundFile;
  execFile("afplay", [soundPath], () => {});
}

export const Dota2Sounds = async ({ project, client, $, directory, worktree }) => {
  // Play start sound on plugin init (session.created fires before plugin loads)
  playSound("start");

  // Track session status to detect busy -> idle transitions (task completion)
  let lastStatus = "idle";

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.status": {
          const status = event.properties?.status?.type;
          // busy -> idle = agent finished responding
          if (lastStatus === "busy" && (status === "idle" || status === "done")) {
            playSound("success");
          }
          if (status) lastStatus = status;
          break;
        }
        case "session.error":
          playSound("error");
          break;
        case "permission.asked":
          playSound("attention");
          break;
        case "session.created":
          playSound("start");
          break;
      }
    },
  };
};
`;
}

/**
 * Install the OpenCode plugin to ~/.config/opencode/plugins/.
 */
export function installOpenCodePlugin(): void {
  const pluginsDir = getOpenCodePluginsDir();
  const pluginPath = getOpenCodePluginPath();
  const soundsDir = getSoundsDir();

  if (!existsSync(pluginsDir)) {
    mkdirSync(pluginsDir, { recursive: true });
  }

  const source = generatePluginSource(soundsDir);
  writeFileSync(pluginPath, source, "utf-8");
}

/**
 * Remove the OpenCode plugin.
 */
export function uninstallOpenCodePlugin(): void {
  const pluginPath = getOpenCodePluginPath();
  if (existsSync(pluginPath)) {
    unlinkSync(pluginPath);
  }
}
