import { existsSync, mkdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { getSoundsDir } from './play-sound.js'

const PLUGIN_FILENAME = 'dota2-sounds.js'

/**
 * Get the path to OpenCode's global plugins directory.
 */
export function getOpenCodePluginsDir(): string {
  return join(homedir(), '.config', 'opencode', 'plugins')
}

/**
 * Get the full path to the plugin file.
 */
export function getOpenCodePluginPath(): string {
  return join(getOpenCodePluginsDir(), PLUGIN_FILENAME)
}

/**
 * Check if OpenCode config directory exists.
 */
export function isOpenCodeAvailable(): boolean {
  return existsSync(join(homedir(), '.config', 'opencode'))
}

/**
 * Generate a self-contained OpenCode plugin JS file.
 * The plugin is fully standalone — no imports from this package at runtime.
 * Sounds are discovered at runtime by scanning the sounds directory.
 */
function generatePluginSource(soundsDir: string): string {
  return `// Auto-generated by dota2-hero-sounds — do not edit manually
// Dota 2 hero voice line notifications for OpenCode
import { execFile } from "node:child_process";
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const DEFAULT_SOUNDS_DIR = ${JSON.stringify(soundsDir)};
const CATEGORY_NAMES = ["success", "error", "attention", "start"];
const NOTIFICATION_EVENTS = ["session_start", "turn_complete", "needs_attention", "error"];
const EVENT_TO_CATEGORY = {
  session_start: "start",
  turn_complete: "success",
  needs_attention: "attention",
  error: "error",
};
const CONFIG_PATH = join(homedir(), ".config", "dota2-sounds", "config.json");

function readConfig() {
  try {
    if (!existsSync(CONFIG_PATH)) return {};
    const raw = readFileSync(CONFIG_PATH, "utf-8");
    return JSON.parse(raw);
  } catch { return {}; }
}

function getSoundsDir() {
  const config = readConfig();
  if (typeof config.soundsDir === "string" && config.soundsDir) return config.soundsDir;
  return DEFAULT_SOUNDS_DIR;
}

function loadSoundCategories() {
  const soundsDir = getSoundsDir();
  const result = {};
  for (const category of CATEGORY_NAMES) {
    const dir = soundsDir + "/" + category;
    if (!existsSync(dir)) {
      result[category] = [];
      continue;
    }
    result[category] = readdirSync(dir)
      .filter((f) => f.endsWith(".mp3"))
      .map((f) => soundsDir + "/" + category + "/" + f);
  }
  return result;
}

function getCategories() {
  return loadSoundCategories();
}

function getConfiguredHeroes() {
  const config = readConfig();
  if (Array.isArray(config.heroes)) return config.heroes;
  return [];
}

function filterByHeroes(sounds, heroes) {
  if (heroes.length === 0) return sounds;
  return sounds.filter((s) => {
    const base = s.split("/").pop() || "";
    return heroes.some((h) => base.startsWith("Vo_" + h + "_"));
  });
}

function getEnabledEvents(config) {
  if (!Array.isArray(config.enabledEvents)) return NOTIFICATION_EVENTS;
  const configured = new Set(config.enabledEvents.filter((event) => NOTIFICATION_EVENTS.includes(event)));
  return NOTIFICATION_EVENTS.filter((event) => configured.has(event));
}

function shouldNotify(event) {
  if (!NOTIFICATION_EVENTS.includes(event)) return false;
  const config = readConfig();
  if (config.muted === true) return false;
  return getEnabledEvents(config).includes(event);
}

const COOLDOWN_MS = 3000;
let lastPlayedAt = 0;

function randomPick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function playSound(category) {
  const now = Date.now();
  if (now - lastPlayedAt < COOLDOWN_MS) return;
  const categories = getCategories();
  let sounds = categories[category] ?? Object.values(categories).flat();
  const heroes = getConfiguredHeroes();
  if (heroes.length > 0) {
    const filtered = filterByHeroes(sounds, heroes);
    if (filtered.length > 0) sounds = filtered;
  }
  if (sounds.length === 0) return;
  const soundPath = randomPick(sounds);
  lastPlayedAt = now;
  execFile("afplay", [soundPath], () => {});
}

function notifyEvent(event) {
  if (!shouldNotify(event)) return;
  const category = EVENT_TO_CATEGORY[event];
  if (!category) return;
  playSound(category);
}

export const Dota2Sounds = async ({ project, client, $, directory, worktree }) => {
  // Play start sound on plugin init (session.created fires before plugin loads)
  notifyEvent("session_start");

  // Track session status to detect busy -> idle transitions (task completion)
  let lastStatus = "idle";

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.status": {
          const status = event.properties?.status?.type;
          // busy -> idle = agent finished responding
          if (lastStatus === "busy" && (status === "idle" || status === "done")) {
            notifyEvent("turn_complete");
          }
          if (status) lastStatus = status;
          break;
        }
        case "session.error":
          notifyEvent("error");
          break;
        case "permission.asked":
          notifyEvent("needs_attention");
          break;
        case "session.created":
          notifyEvent("session_start");
          break;
      }
    },
  };
};
`
}

/**
 * Install the OpenCode plugin to ~/.config/opencode/plugins/.
 */
export function installOpenCodePlugin(soundsDir?: string): void {
  const pluginsDir = getOpenCodePluginsDir()
  const pluginPath = getOpenCodePluginPath()
  const resolvedSoundsDir = soundsDir ?? getSoundsDir()

  if (!existsSync(pluginsDir)) {
    mkdirSync(pluginsDir, { recursive: true })
  }

  const source = generatePluginSource(resolvedSoundsDir)
  writeFileSync(pluginPath, source, 'utf-8')
}

/**
 * Remove the OpenCode plugin.
 */
export function uninstallOpenCodePlugin(): void {
  const pluginPath = getOpenCodePluginPath()
  if (existsSync(pluginPath)) {
    unlinkSync(pluginPath)
  }
}
