import { existsSync, mkdirSync, unlinkSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { getSoundsDir, loadSoundCategories } from './play-sound.js'

const PLUGIN_FILENAME = 'dota2-sounds.js'

/**
 * Get the path to OpenCode's global plugins directory.
 */
export function getOpenCodePluginsDir(): string {
  return join(homedir(), '.config', 'opencode', 'plugins')
}

/**
 * Get the full path to the plugin file.
 */
export function getOpenCodePluginPath(): string {
  return join(getOpenCodePluginsDir(), PLUGIN_FILENAME)
}

/**
 * Check if OpenCode config directory exists.
 */
export function isOpenCodeAvailable(): boolean {
  return existsSync(join(homedir(), '.config', 'opencode'))
}

/**
 * Generate a self-contained OpenCode plugin JS file.
 * The plugin is fully standalone — no imports from this package at runtime.
 * Sound paths are baked in at install time.
 */
function generatePluginSource(soundsDir: string): string {
  const categories = JSON.stringify(loadSoundCategories(), null, 2)

  return `// Auto-generated by dota2-code-sounds — do not edit manually
// Dota 2 Axe voice line notifications for OpenCode
import { execFile } from "node:child_process";

const SOUNDS_DIR = ${JSON.stringify(soundsDir)};

const CATEGORIES = ${categories};

const ALL_SOUNDS = Object.values(CATEGORIES).flat();

const COOLDOWN_MS = 3000;
let lastPlayedAt = 0;

function randomPick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function playSound(category) {
  const now = Date.now();
  if (now - lastPlayedAt < COOLDOWN_MS) return;
  const sounds = CATEGORIES[category] ?? ALL_SOUNDS;
  if (sounds.length === 0) return;
  const soundFile = randomPick(sounds);
  const soundPath = SOUNDS_DIR + "/" + soundFile;
  lastPlayedAt = now;
  execFile("afplay", [soundPath], () => {});
}

export const Dota2Sounds = async ({ project, client, $, directory, worktree }) => {
  // Play start sound on plugin init (session.created fires before plugin loads)
  playSound("start");

  // Track session status to detect busy -> idle transitions (task completion)
  let lastStatus = "idle";

  return {
    event: async ({ event }) => {
      switch (event.type) {
        case "session.status": {
          const status = event.properties?.status?.type;
          // busy -> idle = agent finished responding
          if (lastStatus === "busy" && (status === "idle" || status === "done")) {
            playSound("success");
          }
          if (status) lastStatus = status;
          break;
        }
        case "session.error":
          playSound("error");
          break;
        case "permission.asked":
          playSound("attention");
          break;
        case "session.created":
          playSound("start");
          break;
      }
    },
  };
};
`
}

/**
 * Install the OpenCode plugin to ~/.config/opencode/plugins/.
 */
export function installOpenCodePlugin(): void {
  const pluginsDir = getOpenCodePluginsDir()
  const pluginPath = getOpenCodePluginPath()
  const soundsDir = getSoundsDir()

  if (!existsSync(pluginsDir)) {
    mkdirSync(pluginsDir, { recursive: true })
  }

  const source = generatePluginSource(soundsDir)
  writeFileSync(pluginPath, source, 'utf-8')
}

/**
 * Remove the OpenCode plugin.
 */
export function uninstallOpenCodePlugin(): void {
  const pluginPath = getOpenCodePluginPath()
  if (existsSync(pluginPath)) {
    unlinkSync(pluginPath)
  }
}
